version: ~> 1.0

os: linux
language: python

python: "3.9"

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
    - stage: test
      name: "Flake8"
      install:
        - pip install --upgrade pip setuptools wheel
	- pip install tox
      env:
        - TOXENV=flake8
      script:
        - tox

    - stage: test
      name: "pytest"
      language: python
      python: "3.9"
      install:
        - pip install tox
      script: tox -e py39
      cache: pip
      
    - stage: deploy
      language: generic
      python: "3.9"
      install:
        - pip install --user awscli
      script:
        - python ./setup.py sdist
	- DISTFILE=`find dist/ -type f`
	- aws s3 cp $DISTFILE s3://$S3_DEFAULT_BUCKET/
